// src/app/layout/nav-menu/nav-menu.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { LucideIcons } from '../../core/icons';
import { TournamentService } from '../../core/services/tournament.service';
import { BreakpointService } from '../../core/services/breakpoint.service';

interface NavItem {
  href: string;
  label: string;
  icon: string;
  requiresRunning: boolean;
}

const NAV_ITEMS: NavItem[] = [
  { href: '/', label: 'Torneo', icon: 'Home', requiresRunning: false },
  { href: '/judge', label: 'Vista de Juez', icon: 'Gavel', requiresRunning: true },
  { href: '/life-points', label: 'Puntos de Vida', icon: 'Heart', requiresRunning: false },
  { href: '/angelechy', label: 'Angelechy', icon: 'Crown', requiresRunning: false },
];

/**
 * Persistent side menu. Fully retractable to width 0, leaving only the toggle
 * tab visible attached to its edge (it's a flex sibling of the panel, so it
 * slides with it instead of needing manual position math).
 */
@Component({
  selector: 'app-nav-menu',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, LucideIcons],
  template: `
    <div class="flex h-full items-start bg-background">
      <aside
        class="h-full overflow-hidden border-r transition-[width] duration-300 ease-in-out"
        [class.w-64]="open()"
        [class.w-0]="!open()"
      >
        <div class="flex h-full w-64 flex-col">
          <div class="border-b p-4">
            <h2 class="text-lg font-semibold text-foreground">Menú</h2>
          </div>
          <nav class="flex flex-col gap-1 p-2">
            @for (item of items(); track item.href) {
              <a
                [routerLink]="item.href"
                routerLinkActive="bg-primary text-primary-foreground"
                [routerLinkActiveOptions]="{ exact: item.href === '/' }"
                (click)="onNavigate()"
                class="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium text-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
              >
                <lucide-icon [name]="item.icon" [size]="20" class="shrink-0" />
                {{ item.label }}
              </a>
            }
          </nav>
        </div>
      </aside>

      <button
        type="button"
        class="mt-4 flex h-10 w-6 shrink-0 items-center justify-center rounded-r-md border border-l-0 bg-background shadow-md hover:bg-accent"
        [attr.aria-label]="open() ? 'Cerrar menú' : 'Abrir menú'"
        (click)="toggle()"
      >
        <lucide-icon [name]="open() ? 'ChevronsLeft' : 'ChevronsRight'" [size]="16" />
      </button>
    </div>
  `,
})
export class NavMenuComponent {
  private readonly tournament = inject(TournamentService);
  private readonly breakpoint = inject(BreakpointService);

  protected readonly open = signal(!this.breakpoint.isMobile());

  protected readonly items = computed<NavItem[]>(() => {
    const isRunning = this.tournament.tournament()?.status === 'running';
    return NAV_ITEMS.filter((item) => !item.requiresRunning || isRunning);
  });

  toggle(): void {
    this.open.update((value) => !value);
  }

  onNavigate(): void {
    if (this.breakpoint.isMobile()) {
      this.open.set(false);
    }
  }
}

// src/components/nav-menu.tsx

'use client';

import { useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Crown, Gavel, Heart, Home, Menu } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet';
import { useTournament } from '@/context/tournament-provider';
import { cn } from '@/lib/utils';

const NAV_ITEMS = [
  { href: '/', label: 'Torneo', icon: Home, requiresRunning: false },
  { href: '/judge', label: 'Vista de Juez', icon: Gavel, requiresRunning: true },
  { href: '/life-points', label: 'Puntos de Vida', icon: Heart, requiresRunning: false },
  { href: '/angelechy', label: 'Angelechy', icon: Crown, requiresRunning: false },
];

/**
 * Fully retractable side menu: it stays hidden off-canvas and only slides
 * into view when the header trigger is pressed.
 */
export function NavMenu() {
  const [open, setOpen] = useState(false);
  const pathname = usePathname();
  const { tournament } = useTournament();
  const isRunning = tournament?.status === 'running';

  const items = NAV_ITEMS.filter((item) => !item.requiresRunning || isRunning);

  return (
    <Sheet open={open} onOpenChange={setOpen}>
      <SheetTrigger asChild>
        <Button variant="ghost" size="icon" className="-ml-2 shrink-0" aria-label="Abrir menú">
          <Menu />
        </Button>
      </SheetTrigger>
      <SheetContent side="left" className="flex w-72 max-w-[85vw] flex-col p-0">
        <SheetHeader className="border-b p-4 text-left">
          <SheetTitle>Menú</SheetTitle>
        </SheetHeader>
        <nav className="flex flex-col gap-1 p-2">
          {items.map(({ href, label, icon: Icon }) => {
            const isActive = pathname === href;
            return (
              <Link
                key={href}
                href={href}
                onClick={() => setOpen(false)}
                className={cn(
                  'flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium transition-colors',
                  isActive
                    ? 'bg-primary text-primary-foreground'
                    : 'text-foreground hover:bg-accent hover:text-accent-foreground'
                )}
              >
                <Icon className="h-5 w-5 shrink-0" />
                {label}
              </Link>
            );
          })}
        </nav>
      </SheetContent>
    </Sheet>
  );
}
